version: '3'
services:
  db:
    image: postgres
    container_name: "sql_cookbook_container"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=practice_sql
    ports:
      - "5432:5432"
    volumes:
      - "./db:/var/lib/postgressql/data/"
