version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      MYFINANCE_DB__uri: "postgresql://postgres:postgres@db:5432/${MYFINANCE_DB:-myfinance}"
      MYFINANCE_DB__connect_args: "{}"
    volumes:
      - .:/home/app/api
    depends_on:
      - db
    stdin_open: true
    tty: true
  db:
    build: postgres
    image: myfinance_postgres-13-alpine
    volumes:
      - $HOME/.postgres/myfinance_db/data/postgresql:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    environment:
      - MYFINANCE_DBS=myfinance, myfinance_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres